Clunch\RecipeBundle\Entity\Recipe:
    type: entity
    table: null
    repositoryClass: Clunch\RecipeBundle\Repository\RecipeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        slug:
            type: string
            length: 255
        body:
            type: text
        duration:
            type: time

    manyToOne:
      image:
        targetEntity: Application\Sonata\MediaBundle\Entity\Media
        fetch: EAGER
        joinColumn:
          name: image_id
          referencedColumnName: id

    lifecycleCallbacks: {  }
