Clunch\UserBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: Clunch\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        desc:
            type: text
            nullable: true

    manyToOne:
      picture:
        targetEntity: Application\Sonata\MediaBundle\Entity\Media
        fetch: EAGER
        joinColumn:
          name: picture_id
          referencedColumnName: id

      company:
        targetEntity: Clunch\CompanyBundle\Entity\Company
        inversedBy: users
        joinColumn:
          name: company_id
          referencedColumnName: id
