category:
    resource: "@CategoryBundle/Resources/config/routing.yml"

recipe:
    resource: "@RecipeBundle/Resources/config/routing.yml"

newsletter:
    resource: "@NewsletterBundle/Resources/config/routing.yml"
