Clunch\AllergyBundle\Entity\Allergy:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        title:
            expose: true
        description:
            expose: true

