<?php

namespace Clunch\AllergyBundle\Repository;

/**
 * AllergyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllergyRepository extends \Doctrine\ORM\EntityRepository
{
}
