<?php

namespace Clunch\CategoryBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($search)
    {
        $query = $this->createQueryBuilder("p")
            ->where('p.name LIKE :search')
            ->setParameter('search', "%".$search."%");

        return $query->getQuery()->getResult();
    }
}
