Clunch\NewsletterBundle\Entity\Newsletter:
    type: entity
    table: null
    repositoryClass: Clunch\NewsletterBundle\Repository\NewsletterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mail:
            type: string
            length: 255
            unique: true
        phone:
            type: string
            length: 255
            unique: true
        agreement:
            type: boolean
    lifecycleCallbacks: {  }
